add link to new google groups forum
jbosstm/narayana.io pull request #23
Opened 2020-03-03 16:30 UTC by mmusgrov

Add link to new forum

2020-03-09 12:09 UTC, ochaloup requested changes
The link works fine just I think this PR should be enhanced. The PR changes the link only at teh community page. But the narayana.io contains the link at three more places

- `documentation/index.html.haml`
- `_layouts/project.html.haml`
- `_partials/forum-posts.html.haml`

Then narayana.io has the right panel with "Latest forum discussions" which should be either removed or provided with a functionality of loading data from google groups, I assume.

2020-06-08 11:14 UTC, tomjenkinson commented
I think for now we would remove the "latest forum discussions" (https://github.com/jbosstm/narayana.io/blob/develop/_partials/rightcol.html.haml#L30-L43). We can raise a task to add something back later. I assume that we might need to remove  "more forum posts" ( _partials/forum-posts.html.haml) too.

I agree that _layouts/project.html.haml need an update to link to the new forums too.

I think the link on documentation/index.html.haml to the wiki is OK for now, but we should move the Wiki.

2020-06-08 11:16 UTC, tomjenkinson commented
@mmusgrov: https://github.com/jbosstm/narayana.io/commit/334c0e7a814928bfd17e9153d43c6c9da95ac05d#diff-09e9b4a5ca926819e94f2274f10b5bdb is already in the develop branch and live on the site: https://narayana.io/community/index.html

2020-07-07 10:59 UTC, mmusgrov commented
I am temporarily closing this PR

2020-07-07 10:59 UTC, closed without merging